[project]
name = "truck-driver"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pyray>=0.1.0",
    "raylib>=5.5.0.2",
    "ruff>=0.9.6",
]
